FROM balenalib/rpi-raspbian:buster

# Enforces cross-compilation through Quemu
RUN [ "cross-build-start" ]

WORKDIR /app

RUN apt-get update -y
RUN apt-get install -y \
    python3 \
    python3-pip \
    python3-dev

COPY requirements.txt ./
RUN pip3 install -r requirements.txt

# Cleanup
RUN rm -rf /var/lib/apt/lists/* \
    && apt-get -y autoremove

RUN [ "cross-build-end" ]

COPY . .

CMD [ "python3", "-u", "./main.py" ]