FROM arm32v7/python:3.7-slim-buster

WORKDIR /app

RUN apt-get update
RUN apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y \
    cmake \
    build-essential \
    pkg-config \
    libopenjp2-7-dev \
    zlib1g-dev \
    libcurl4-openssl-dev

COPY requirements.txt ./
RUN pip install -U pip
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]